In [95]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
import numpy as np


heart_data = pd.read_csv('./heart_disease_dataset/processed.cleveland.csv')

heart_data.dropna()
heart_data.head()
heart_data.shape
# heart_data.info()


(303, 14)

In [96]:
# Separate features (X) and target (y)
X = heart_data.drop(columns='condition')   # Replace 'target' with the actual target column name

y = heart_data['condition']

heart_data.shape
heart_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        303 non-null    float64
 1   sex        303 non-null    float64
 2   cp         303 non-null    float64
 3   trestbps   303 non-null    float64
 4   chol       303 non-null    float64
 5   fbs        303 non-null    float64
 6   restecg    303 non-null    float64
 7   thalach    303 non-null    float64
 8   exang      303 non-null    float64
 9   oldpeak    303 non-null    float64
 10  slope      303 non-null    float64
 11  ca         303 non-null    object 
 12  thal       303 non-null    object 
 13  condition  303 non-null    int64  
dtypes: float64(11), int64(1), object(2)
memory usage: 33.3+ KB


In [97]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = X_train.replace('?', np.nan)
X_test = X_test.replace('?', np.nan)


print(X_train.shape)
print(X_train.head())



(242, 13)
      age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
132  29.0  1.0  2.0     130.0  204.0  0.0      2.0    202.0    0.0      0.0   
202  57.0  1.0  3.0     150.0  126.0  1.0      0.0    173.0    0.0      0.2   
196  69.0  1.0  1.0     160.0  234.0  1.0      2.0    131.0    0.0      0.1   
75   65.0  0.0  3.0     160.0  360.0  0.0      2.0    151.0    0.0      0.8   
176  52.0  1.0  4.0     108.0  233.0  1.0      0.0    147.0    0.0      0.1   

     slope   ca thal  
132    1.0  0.0  3.0  
202    1.0  1.0  7.0  
196    2.0  1.0  3.0  
75     1.0  0.0  3.0  
176    1.0  3.0  7.0  


In [98]:
print(X_train.isnull().sum())

X_train = X_train.dropna()
y_train = y_train[X_train.index]  # Ensure `y_train` matches the updated `X_train`

X_test = X_test.dropna()
y_test = y_test[X_test.index]  # Ensure `y_test` matches the updated `X_test`

heart_data.shape
print(X_train.shape)
print(X_train.isnull().sum())



age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          3
thal        2
dtype: int64
(237, 13)
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
dtype: int64


In [99]:


# Scaling the data.
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression Model
model = LogisticRegression(solver='saga', max_iter=10000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.5666666666666667


In [100]:
new_data = X.iloc[3]  # Select the first row from your features
new_data = new_data.values.reshape(1, -1)  # Convert to a 2D array
new_data = new_data.reshape(1, -1)
X_new = pd.DataFrame(new_data, columns=X_train.columns)
predictions = model.predict(X_new)
print("Prediction for new data:", predictions)

Prediction for new data: [0]


In [101]:
X.iloc[4]

age          41.0
sex           0.0
cp            2.0
trestbps    130.0
chol        204.0
fbs           0.0
restecg       2.0
thalach     172.0
exang         0.0
oldpeak       1.4
slope         1.0
ca            0.0
thal          3.0
Name: 4, dtype: object

In [102]:
from sklearn.tree import DecisionTreeClassifier

# Train decision tree model
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

# Make predictions
y_pred_tree = tree.predict(X_test)

# Evaluate
print("Decision Tree Performance:")
print(classification_report(y_test, y_pred_tree))


Decision Tree Performance:
              precision    recall  f1-score   support

           0       0.71      0.86      0.78        29
           1       0.00      0.00      0.00        11
           2       0.00      0.00      0.00         9
           3       0.11      0.14      0.12         7
           4       0.00      0.00      0.00         4

    accuracy                           0.43        60
   macro avg       0.17      0.20      0.18        60
weighted avg       0.36      0.43      0.39        60



In [103]:
from sklearn.ensemble import RandomForestClassifier

# Train random forest model
forest = RandomForestClassifier(random_state=42, n_estimators=100)
forest.fit(X_train, y_train)

# Make predictions
y_pred_forest = forest.predict(X_test)

# Evaluate
print("Random Forest Performance:")
print(classification_report(y_test, y_pred_forest))


Random Forest Performance:
              precision    recall  f1-score   support

           0       0.74      0.97      0.84        29
           1       0.29      0.18      0.22        11
           2       0.12      0.11      0.12         9
           3       0.14      0.14      0.14         7
           4       0.00      0.00      0.00         4

    accuracy                           0.53        60
   macro avg       0.26      0.28      0.26        60
weighted avg       0.44      0.53      0.48        60



c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [104]:
print(X_train.dtypes)

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit and transform the training data
encoded_train = encoder.fit_transform(X_train[['ca', 'thal']])
encoded_train_df = pd.DataFrame(encoded_train, columns=encoder.get_feature_names_out(['ca', 'thal']))

# Transform the test data
encoded_test = encoder.transform(X_test[['ca', 'thal']])
encoded_test_df = pd.DataFrame(encoded_test, columns=encoder.get_feature_names_out(['ca', 'thal']))

# Drop the original columns and concatenate the encoded columns
X_train = X_train.drop(['ca', 'thal'], axis=1).reset_index(drop=True)
X_test = X_test.drop(['ca', 'thal'], axis=1).reset_index(drop=True)

X_train = pd.concat([X_train, encoded_train_df], axis=1)
X_test = pd.concat([X_test, encoded_test_df], axis=1)

age         float64
sex         float64
cp          float64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca           object
thal         object
dtype: object


In [105]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# Assuming X and y are already defined
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert 'ca' and 'thal' to categorical data type
X_train['ca'] = X_train['ca'].astype('category')
X_train['thal'] = X_train['thal'].astype('category')

X_test['ca'] = X_test['ca'].astype('category')
X_test['thal'] = X_test['thal'].astype('category')

# Initialize and train the model
xgb = XGBClassifier(n_estimators=100, max_depth=4, learning_rate=0.1, random_state=42, enable_categorical=True)
xgb.fit(X_train, y_train)

# Make predictions
y_pred = xgb.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))



Accuracy: 0.5245901639344263
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.93      0.83        29
           1       0.18      0.17      0.17        12
           2       0.14      0.11      0.12         9
           3       0.29      0.29      0.29         7
           4       0.00      0.00      0.00         4

    accuracy                           0.52        61
   macro avg       0.27      0.30      0.28        61
weighted avg       0.45      0.52      0.48        61



c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [114]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

# Assuming 'heart_data' is your original DataFrame
original_column_names = heart_data.columns[:X_train.shape[1]]  # Ensure the column names match the data shape

# Convert X_train and X_test to DataFrames
X_train = pd.DataFrame(X_train, columns=original_column_names)
X_test = pd.DataFrame(X_test, columns=original_column_names)

# Replace '?' with NaN
X_train = X_train.replace('?', np.nan)
X_test = X_test.replace('?', np.nan)

# Impute missing values with the mean
imputer = SimpleImputer(strategy='mean')
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  # Corrected here
X_test_scaled = scaler.transform(X_test)

# Apply SMOTE to resample the training data
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_scaled, y_train)

# Apply RandomUnderSampler to resample the training data
undersampler = RandomUnderSampler(random_state=42)
X_train_resampled, y_train_resampled = undersampler.fit_resample(X_train_scaled, y_train)

print("Resampled class distribution:", pd.Series(y_train_resampled).value_counts())

# Print shapes of X_train and X_test
print(X_train.shape)  # Should return (242, 13)
print(X_test.shape)   # Should return the shape of your test data

# Train Logistic Regression model
model = LogisticRegression(solver='saga', max_iter=10000, class_weight='balanced', C=0.1)
scores = cross_val_score(model, X_train_resampled, y_train_resampled, cv=5)
print("Cross-validation scores:", scores)
print("Mean accuracy:", scores.mean())
model.fit(X_train_resampled, y_train_resampled)

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Resampled class distribution: condition
0    9
1    9
2    9
3    9
4    9
Name: count, dtype: int64
(242, 13)
(61, 13)
Cross-validation scores: [0.11111111 0.22222222 0.22222222 0.11111111 0.33333333]
Mean accuracy: 0.2
Accuracy: 0.5245901639344263
Confusion Matrix:
[[24  2  2  1  0]
 [ 4  1  2  4  1]
 [ 2  0  4  1  2]
 [ 0  2  2  2  1]
 [ 0  1  2  0  1]]

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.83      0.81        29
           1       0.17      0.08      0.11        12
           2       0.33      0.44      0.38         9
           3       0.25      0.29      0.27         7
           4       0.20      0.25      0.22         4

    accuracy                           0.52        61
   macro avg       0.35      0.38      0.36        61
weighted avg       0.50      0.52      0.51        61



In [ ]:
# Print the value counts of the target variable in both training and testing sets
print("Training set target variable counts:")
print(y_train.value_counts())
print(y_test.value_counts())

Training set target variable counts:
condition
0    135
1     43
3     28
2     27
4      9
Name: count, dtype: int64
condition
0    29
1    12
2     9
3     7
4     4
Name: count, dtype: int64


In [108]:
# Save the model
import joblib

joblib.dump(model, 'model.pkl')

['model.pkl']